### ISSUE TITLE
Add in sponsor logos

### ISSUE THREAD

**Issue by EmHain8** [foss4g-oceania/foss4g-sotm-oceania-2023#11]
Please add in the sponsor logos to the Home page and also a page under sponsorship with some more information

**Comment by eneerhut** [comment]
We need to add a sponsor section on the main page with the following levels. I will update this as sponsors pay. 

**Platinum**

**Gold**

**Silver**
Nova Systems
![NOVA-SYSTEMS.png](https://github.com/foss4g-oceania/foss4g-sotm-oceania-2023/assets/11349863/cb65da8d-bb63-4ec3-8dfa-ddb2a4b42777)



Orbica
![image001.jpg](https://github.com/foss4g-oceania/foss4g-sotm-oceania-2023/assets/11349863/f9871f3f-a1c6-4575-9e41-a3bac1bde860)



**Bronze**
North Road
![nr_header_logo.png](https://github.com/foss4g-oceania/foss4g-sotm-oceania-2023/assets/11349863/7c93d28f-e4f6-4975-83e4-3d576073e228)



**Supporter**

**Comment by EmHain8** [comment]
If you can't use the logos above, you can get them from here: https://drive.google.com/drive/u/1/folders/1XvDHxZGucPqxfp6XTkqKEM2SK_Kc45hw

**Comment by EmHain8** [comment]
[Linux Australia](https://linux.org.au/)
[North Road](https://north-road.com/)
[Nova Systems](https://www.novasystems.com/)
[Orbica](https://www.orbica.com/)
[Soar](https://soar.earth/)
[LINZ](https://www.linz.govt.nz/)
[OpenWork Ltd](https://www.openwork.nz/)
[Locate Press](https://locatepress.com/)
[Facebook - Meta](https://www.meta.com/au/)
[Koordinates](https://koordinates.com/)
[TomTom](https://www.tomtom.com/)

**Comment by EmHain8** [comment]
Testing

- [ ] AUT](https://www.aut.ac.nz/)
- [ ] Linux Australia](https://linux.org.au/)
- [ ] North Road](https://north-road.com/)
- [ ] Nova Systems](https://www.novasystems.com/)
- [ ] Orbica](https://www.orbica.com/)
- [ ] Soar](https://soar.earth/)
- [ ] TomTom](https://www.tomtom.com/)
- [ ] LINZ](https://www.linz.govt.nz/)
- [ ] OpenWork Ltd](https://www.openwork.nz/)
- [ ] Locate Press](https://locatepress.com/)
- [ ] Facebook - Meta](https://www.meta.com/au/)
- [ ] Koordinates](https://koordinates.com/)

**Comment by EmHain8** [comment]
tomtom - wrong address sorry - https://www.novasystems.com/nz

**Comment by EmHain8** [comment]
As sponsors pay, we will reactive their logos
